export const InboxInterface = () => {
  return (
    <div className="bg-[lab(98.84_0.0000298023_-0.0000119209)] box-border caret-transparent flex flex-col h-[720px] min-h-[720px] w-full overflow-hidden md:h-full md:min-h-0">
      <div className="items-center box-border caret-transparent gap-x-2 flex justify-between min-h-0 min-w-0 gap-y-2 border-[oklab(0.205_-0.00000207871_0.00000478327_/_0.1)] px-4 py-1 border-b border-solid md:min-h-[auto] md:min-w-[auto]">
        <div className="box-border caret-transparent gap-x-2 flex min-h-0 min-w-0 gap-y-2 w-20 md:min-h-[auto] md:min-w-[auto]">
          <div className="bg-[lab(55.4814_75.0732_48.8528)] box-border caret-transparent h-2 min-h-0 min-w-0 w-2 rounded-[3.35544e+07px] md:min-h-[auto] md:min-w-[auto]"></div>
          <div className="bg-[lab(76.3898_14.5258_98.4589)] box-border caret-transparent h-2 min-h-0 min-w-0 w-2 rounded-[3.35544e+07px] md:min-h-[auto] md:min-w-[auto]"></div>
          <div className="bg-[lab(70.5521_-66.5147_45.8073)] box-border caret-transparent h-2 min-h-0 min-w-0 w-2 rounded-[3.35544e+07px] md:min-h-[auto] md:min-w-[auto]"></div>
        </div>
        <div className="items-center bg-[lab(98.84_0.0000298023_-0.0000119209)] box-border caret-transparent gap-x-2 flex basis-[0%] grow justify-center min-h-0 min-w-0 gap-y-2 ml-4 px-3 py-1.5 md:min-h-[auto] md:min-w-[auto]">
          <span className="text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.6)] text-xs bg-[lab(93.04_0.0000298023_-0.0000119209)] box-border caret-transparent block leading-4 min-h-0 min-w-0 px-2 py-1 rounded-md md:min-h-[auto] md:min-w-[auto]">
            https://cossistant.com/shadcn/inbox
          </span>
        </div>
        <div className="box-border caret-transparent min-h-0 min-w-0 w-20 md:min-h-[auto] md:min-w-[auto]"></div>
      </div>
      <div className="bg-[lab(98.84_0.0000298023_-0.0000119209)] box-border caret-transparent basis-[0%] grow min-h-0 min-w-0 md:min-h-[auto] md:min-w-[auto]">
        <div className="box-border caret-transparent h-[684px] w-full md:h-[800px]">
          <div className="relative bg-[lab(97.68_-0.0000298023_0.0000119209)] box-border caret-transparent flex flex-col h-full w-full overflow-hidden">
            <header className="items-center box-border caret-transparent gap-x-4 flex h-16 justify-between min-h-16 min-w-0 pointer-events-none gap-y-4 w-full pl-[26px] pr-3 md:min-w-[auto]">
              <div className="items-center box-border caret-transparent gap-x-3 flex basis-[0%] grow min-h-0 min-w-0 gap-y-3 md:min-h-[auto] md:min-w-[auto]">
                <a
                  href="/"
                  className="box-border caret-transparent block min-h-0 min-w-0 mr-2 md:min-h-[auto] md:min-w-[auto]"
                >
                  <img
                    src="https://c.animaapp.com/mlnjf5yy2zLUvi/assets/icon-4.svg"
                    alt="Icon"
                    className="text-[lab(7.78201_-0.0000149012_0)] box-border caret-transparent h-[22px] w-[22px]"
                  />
                </a>
                <a
                  href="/agent"
                  className="relative text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.8)] text-sm items-center box-border caret-transparent gap-x-2 flex leading-5 min-h-0 min-w-0 gap-y-2 p-1 rounded-sm md:min-h-[auto] md:min-w-[auto] md:px-2"
                >
                  <span className="box-border caret-transparent hidden basis-[0%] grow min-h-0 min-w-0 text-ellipsis text-nowrap overflow-hidden md:block md:min-h-[auto] md:min-w-[auto]">
                    <span className="items-center box-border caret-transparent gap-x-1.5 flex gap-y-1.5 text-nowrap">
                      Agent
                      <span className="text-white text-[10px] font-medium bg-orange-600 box-border caret-transparent block leading-[10px] min-h-0 min-w-0 text-nowrap px-1.5 py-0.5 rounded-sm md:min-h-[auto] md:min-w-[auto]">
                        AI
                      </span>
                    </span>
                  </span>
                </a>
              </div>
              <div className="items-center box-border caret-transparent gap-x-3 flex min-h-0 min-w-0 gap-y-3 mr-2 md:min-h-[auto] md:min-w-[auto]">
                <a
                  href="/contacts"
                  className="relative text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.8)] text-sm items-center box-border caret-transparent gap-x-2 flex leading-5 min-h-0 min-w-0 gap-y-2 p-1 rounded-sm md:min-h-[auto] md:min-w-[auto] md:px-2"
                >
                  <span className="box-border caret-transparent hidden basis-[0%] grow min-h-0 min-w-0 text-ellipsis text-nowrap overflow-hidden md:block md:min-h-[auto] md:min-w-[auto]">
                    Contacts
                  </span>
                </a>
                <div className="relative text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.8)] text-sm items-center box-border caret-transparent gap-x-2 flex leading-5 min-h-0 min-w-0 gap-y-2 px-2 py-1 rounded-sm md:min-h-[auto] md:min-w-[auto]">
                  <img
                    src="https://c.animaapp.com/mlnjf5yy2zLUvi/assets/icon-5.svg"
                    alt="Icon"
                    className="box-border caret-transparent h-4 w-4"
                  />
                  <span className="font-medium box-border caret-transparent block min-h-0 min-w-0 md:min-h-[auto] md:min-w-[auto]">
                    Need help?
                  </span>
                </div>
              </div>
            </header>
            <div className="box-border caret-transparent flex basis-[0%] grow h-[612px] min-w-0 w-full pb-2 px-2 md:h-[736px] md:min-w-[auto]">
              <section className="bg-[lab(98.84_0.0000298023_-0.0000119209)] box-border caret-transparent flex basis-[0%] grow h-full max-h-full min-w-0 border border-[oklab(0.205_-0.00000207871_0.00000478327_/_0.1)] overflow-clip rounded-sm border-solid md:min-w-[auto]">
                <aside className="static box-content caret-black block min-h-0 min-w-0 pointer-events-auto w-auto border-r-0 md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-72 md:border-[oklab(0.205_-0.00000207871_0.00000478327_/_0.1)] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:border-r md:border-solid">
                  <div className="static box-content caret-black gap-x-[normal] block flex-row min-h-0 min-w-0 gap-y-[normal] w-auto md:relative md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:flex-col md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:p-2 md:scroll-m-0 md:scroll-p-[auto]">
                    <div className="box-content caret-black gap-x-[normal] block basis-auto flex-row grow-0 max-h-none min-h-0 min-w-0 gap-y-[normal] md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:basis-[0%] md:flex-col md:grow md:max-h-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <a
                        href="/"
                        className="static text-black text-base [align-items:normal] bg-transparent box-content caret-black gap-x-[normal] inline h-auto leading-[normal] min-h-0 min-w-0 gap-y-[normal] p-0 rounded-none md:relative md:text-[lab(7.78201_-0.0000149012_0)] md:text-sm md:items-center md:aspect-auto md:bg-[lab(97.68_-0.0000298023_0.0000119209)] md:box-border md:caret-transparent md:gap-x-2.5 md:flex md:h-10 md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:px-3 md:py-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm"
                      >
                        <span className="box-content caret-black inline basis-auto grow-0 min-h-0 min-w-0 text-clip text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:basis-[0%] md:grow md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          Inbox
                        </span>
                        <span className="text-black text-base box-content caret-black inline leading-[normal] min-h-0 min-w-0 pr-0 md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.4)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-1 md:scroll-m-0 md:scroll-p-[auto]">
                          10
                        </span>
                      </a>
                      <a
                        href="/resolved"
                        className="static text-black text-base [align-items:normal] box-content caret-black gap-x-[normal] inline h-auto leading-[normal] min-h-0 min-w-0 gap-y-[normal] p-0 rounded-none md:relative md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.8)] md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2.5 md:flex md:h-10 md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:px-3 md:py-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm"
                      >
                        <span className="box-content caret-black inline basis-auto grow-0 min-h-0 min-w-0 text-clip text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:basis-[0%] md:grow md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          Resolved
                        </span>
                      </a>
                      <a
                        href="/spam"
                        className="static text-black text-base [align-items:normal] box-content caret-black gap-x-[normal] inline h-auto leading-[normal] min-h-0 min-w-0 gap-y-[normal] p-0 rounded-none md:relative md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.8)] md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2.5 md:flex md:h-10 md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:px-3 md:py-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm"
                      >
                        <span className="box-content caret-black inline basis-auto grow-0 min-h-0 min-w-0 text-clip text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:basis-[0%] md:grow md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          Spam
                        </span>
                      </a>
                      <a
                        href="/archived"
                        className="static text-black text-base [align-items:normal] box-content caret-black gap-x-[normal] inline h-auto leading-[normal] min-h-0 min-w-0 gap-y-[normal] p-0 rounded-none md:relative md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.8)] md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2.5 md:flex md:h-10 md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:px-3 md:py-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm"
                      >
                        <span className="box-content caret-black inline basis-auto grow-0 min-h-0 min-w-0 text-clip text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:basis-[0%] md:grow md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          Archived
                        </span>
                      </a>
                    </div>
                    <a
                      href="/docs"
                      className="static text-black text-base [align-items:normal] box-content caret-black gap-x-[normal] inline h-auto leading-[normal] min-h-0 min-w-0 gap-y-[normal] p-0 rounded-none md:relative md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.8)] md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2.5 md:flex md:h-10 md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:px-3 md:py-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm"
                    >
                      <span className="box-content caret-black inline basis-auto grow-0 min-h-0 min-w-0 text-clip text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:basis-[0%] md:grow md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        Docs
                      </span>
                    </a>
                    <a
                      href="/settings"
                      className="static text-black text-base [align-items:normal] box-content caret-black gap-x-[normal] inline h-auto leading-[normal] min-h-0 min-w-0 gap-y-[normal] p-0 rounded-none md:relative md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.8)] md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2.5 md:flex md:h-10 md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:px-3 md:py-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm"
                    >
                      <span className="box-content caret-black inline basis-auto grow-0 min-h-0 min-w-0 text-clip text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:basis-[0%] md:grow md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        Settings
                      </span>
                    </a>
                    <div
                      role="none"
                      className="bg-transparent box-content caret-black shrink h-auto min-h-0 min-w-0 opacity-100 w-auto md:aspect-auto md:bg-[lab(90.952_0_-0.0000119209)] md:box-border md:caret-transparent md:shrink-0 md:h-px md:min-h-[auto] md:min-w-[auto] md:opacity-30 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                    ></div>
                    <button
                      type="button"
                      className="text-black text-[13.3333px] [align-items:normal] bg-zinc-100 caret-black gap-x-[normal] inline-block leading-[normal] min-h-0 min-w-0 gap-y-[normal] text-center px-1.5 py-px rounded-none md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.8)] md:text-sm md:items-center md:aspect-auto md:bg-transparent md:caret-transparent md:gap-x-2.5 md:flex md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2.5 md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:px-3 md:py-2.5 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm"
                    >
                      <div className="box-content caret-black block basis-auto grow-0 leading-[normal] min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:grid md:basis-[0%] md:grow md:leading-[17.5px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <div className="bg-transparent box-content caret-black h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-[lab(95.36_0_0)] md:box-border md:caret-transparent md:h-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-24 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm"></div>
                      </div>
                      <div className="bg-transparent box-content caret-black h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-[lab(95.36_0_0)] md:box-border md:caret-transparent md:h-5 md:min-h-[auto] md:min-w-5 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm"></div>
                    </button>
                  </div>
                </aside>
                <div className="static box-content caret-black block basis-auto flex-row grow-0 h-auto min-h-0 min-w-0 md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:basis-[0%] md:flex-col md:grow md:h-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <div className="static [align-items:normal] bg-transparent box-content caret-black gap-x-[normal] block h-auto justify-normal gap-y-[normal] w-auto z-auto px-0 top-auto inset-x-auto md:absolute md:items-center md:aspect-auto md:bg-[lab(98.84_0.0000298023_-0.0000119209)] md:box-border md:caret-transparent md:gap-x-4 md:flex md:h-14 md:justify-between md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-10 md:[mask-position:0%] md:bg-left-top md:px-4 md:scroll-m-0 md:scroll-p-[auto] md:top-0 md:inset-x-0">
                    <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <h3 className="text-black text-[18.72px] font-bold box-content caret-black leading-[normal] min-h-0 min-w-0 normal-case md:text-[lab(7.78201_-0.0000149012_0)] md:text-sm md:font-medium md:aspect-auto md:box-border md:caret-transparent md:leading-5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:capitalize md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        Inbox
                      </h3>
                    </div>
                  </div>
                  <div className="static box-content caret-black block basis-auto flex-row grow-0 h-auto min-h-0 min-w-0 overflow-x-visible overflow-y-visible p-0 md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:basis-[0%] md:flex-col md:grow md:h-full md:min-h-[auto] md:min-w-[auto] md:overflow-x-hidden md:overflow-y-scroll md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pt-14 md:pb-4 md:px-4 md:scroll-m-0 md:scroll-p-[auto]">
                    <div className="box-content caret-black h-auto min-h-0 min-w-0 overflow-x-visible overflow-y-visible md:aspect-auto md:box-border md:caret-transparent md:h-full md:min-h-[auto] md:min-w-[auto] md:overflow-x-hidden md:overflow-y-scroll md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <div className="box-content caret-black pb-0 md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pb-10 md:scroll-m-0 md:scroll-p-[auto]">
                        <div className="box-content caret-black md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                          <div className="box-content caret-black gap-x-[normal] block gap-y-[normal] md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <div className="box-content caret-black block basis-auto flex-row grow-0 h-auto justify-normal min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:flex md:basis-[0%] md:flex-col md:grow md:h-[42px] md:justify-between md:min-h-[auto] md:min-w-[150px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              <p className="text-black text-base box-content caret-black leading-[normal] min-h-0 min-w-0 md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.6)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                Median response time
                              </p>
                              <div className="[align-items:normal] box-content caret-black gap-x-[normal] block justify-normal min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:justify-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] md:items-baseline md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  <span className="text-black font-normal box-content caret-black inline min-h-0 min-w-0 md:text-[lab(7.78201_-0.0000149012_0)] md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                    5m 20s
                                  </span>
                                </div>
                                <span className="text-black text-base font-normal box-content caret-black inline leading-[normal] min-h-0 min-w-0 md:text-[lab(55.0481_-49.9246_15.93)] md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  -22%
                                </span>
                              </div>
                            </div>
                            <div className="box-content caret-black block basis-auto flex-row grow-0 h-auto justify-normal min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:flex md:basis-[0%] md:flex-col md:grow md:h-[42px] md:justify-between md:min-h-[auto] md:min-w-[150px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              <p className="text-black text-base box-content caret-black leading-[normal] min-h-0 min-w-0 md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.6)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                Median time to resolution
                              </p>
                              <div className="[align-items:normal] box-content caret-black gap-x-[normal] block justify-normal min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:justify-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] md:items-baseline md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  <span className="text-black font-normal box-content caret-black inline min-h-0 min-w-0 md:text-[lab(7.78201_-0.0000149012_0)] md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                    1h 30m
                                  </span>
                                </div>
                                <span className="text-black text-base font-normal box-content caret-black inline leading-[normal] min-h-0 min-w-0 md:text-[lab(55.0481_-49.9246_15.93)] md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  -11%
                                </span>
                              </div>
                            </div>
                            <div className="box-content caret-black block basis-auto flex-row grow-0 h-auto justify-normal min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:flex md:basis-[0%] md:flex-col md:grow md:h-[42px] md:justify-between md:min-h-[auto] md:min-w-[150px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              <p className="text-black text-base box-content caret-black leading-[normal] min-h-0 min-w-0 md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.6)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                % handled by AI
                              </p>
                              <div className="[align-items:normal] box-content caret-black gap-x-[normal] block justify-normal min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:justify-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] md:items-baseline md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  <span className="text-black font-normal box-content caret-black inline min-h-0 min-w-0 md:text-[lab(7.78201_-0.0000149012_0)] md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                    62%
                                  </span>
                                </div>
                                <span className="text-black text-base font-normal box-content caret-black inline leading-[normal] min-h-0 min-w-0 md:text-[lab(55.0481_-49.9246_15.93)] md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  +13%
                                </span>
                              </div>
                            </div>
                            <div className="box-content caret-black block basis-auto flex-row grow-0 h-auto justify-normal min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:flex md:basis-[0%] md:flex-col md:grow md:h-[42px] md:justify-between md:min-h-[auto] md:min-w-[150px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              <p className="text-black text-base box-content caret-black leading-[normal] min-h-0 min-w-0 md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.6)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                Satisfaction index
                              </p>
                              <div className="[align-items:normal] box-content caret-black gap-x-[normal] block justify-normal min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:justify-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] md:items-baseline md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  <span className="text-black font-normal box-content caret-black inline min-h-0 min-w-0 md:text-[lab(7.78201_-0.0000149012_0)] md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                    86
                                  </span>
                                  <span className="text-black text-base box-content caret-black inline leading-[normal] min-h-0 min-w-0 md:text-[lab(48.496_0_0)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                    /100
                                  </span>
                                </div>
                                <span className="text-black text-base font-normal box-content caret-black inline leading-[normal] min-h-0 min-w-0 md:text-[lab(55.0481_-49.9246_15.93)] md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  +5%
                                </span>
                              </div>
                            </div>
                            <div className="box-content caret-black block basis-auto flex-row grow-0 h-auto justify-normal min-h-0 min-w-0 md:aspect-auto md:box-border md:caret-transparent md:flex md:basis-[0%] md:flex-col md:grow md:h-[42px] md:justify-between md:min-h-[auto] md:min-w-[150px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              <p className="text-black text-base box-content caret-black leading-[normal] min-h-0 min-w-0 md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.6)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                Unique visitors
                              </p>
                              <div className="[align-items:normal] box-content caret-black gap-x-[normal] block justify-normal min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:justify-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] md:items-baseline md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  <span className="text-black font-normal box-content caret-black inline min-h-0 min-w-0 md:text-[lab(7.78201_-0.0000149012_0)] md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                    1,280
                                  </span>
                                </div>
                                <span className="text-black text-base font-normal box-content caret-black inline leading-[normal] min-h-0 min-w-0 md:text-[lab(55.0481_-49.9246_15.93)] md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:block md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  +13%
                                </span>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="box-content caret-black md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <div className="static text-base [align-items:normal] box-content caret-black gap-x-[normal] block leading-[normal] gap-y-[normal] rounded-none md:relative md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:leading-5 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-2 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm">
                          <div className="static box-content caret-black min-h-0 min-w-0 md:relative md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <span className="static shadow-none box-content caret-black inline shrink h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,lab(98.84_0.0000298023_-0.0000119209)_0px_0px_0px_1px,lab(90.952_0_-0.0000119209)_0px_0px_0px_2px,rgba(0,0,0,0)_0px_0px_0px_0px] md:box-border md:caret-transparent md:flex md:shrink-0 md:h-8 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-8 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm">
                              <span className="[align-items:normal] box-content caret-black inline h-auto justify-normal min-h-0 min-w-0 pointer-events-auto w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-full md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <div className="static text-black [align-items:normal] bg-transparent box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto md:relative md:items-center md:aspect-auto md:bg-[oklab(0.608388_0.155916_0.122386_/_0.2)] md:box-border md:caret-transparent md:flex md:h-full md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  <div className="static bg-none box-content caret-black z-auto inset-auto md:absolute md:aspect-auto md:bg-[radial-gradient(100%_100%,rgba(255,255,255,0.15)_0%,rgba(0,0,0,0)_60%)] md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                                  <div className="static [align-items:normal] box-content caret-black block flex-row justify-normal transform-none z-auto inset-auto md:absolute md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
                                    <img
                                      src="https://c.animaapp.com/mlnjf5yy2zLUvi/assets/icon-6.svg"
                                      alt="Icon"
                                      className="box-content caret-black w-auto md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-3/5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                                    />
                                    <span className="text-base box-content caret-black inline leading-[normal] min-h-0 min-w-0 mt-0 md:text-[8.32px] md:aspect-auto md:box-border md:caret-transparent md:block md:leading-[8.32px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[8%] md:scroll-m-0 md:scroll-p-[auto]">
                                      P
                                    </span>
                                  </div>
                                </div>
                              </span>
                            </span>
                            <div className="static bg-transparent shadow-none box-content caret-black h-auto w-auto rounded-none right-auto bottom-auto md:absolute md:aspect-auto md:bg-emerald-500 md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,lab(98.84_0.0000298023_-0.0000119209)_0px_0px_0px_2px,rgba(0,0,0,0)_0px_0px_0px_0px] md:box-border md:caret-transparent md:h-[5px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[5px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px] md:-right-1 md:bottom-0.5"></div>
                          </div>
                          <div className="[align-items:normal] box-content caret-black gap-x-[normal] block basis-auto grow-0 min-h-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <p className="box-content caret-black shrink max-w-none min-h-0 min-w-0 text-clip normal-case text-wrap md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:max-w-[140px] md:min-h-[auto] md:min-w-[140px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:capitalize md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              Pieter Levels
                            </p>
                            <div className="[align-items:normal] box-content caret-black gap-x-[normal] block basis-auto grow-0 min-h-0 gap-y-[normal] pr-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-6 md:scroll-m-0 md:scroll-p-[auto]">
                              <span className="text-black [align-items:normal] box-content caret-black gap-x-[normal] inline basis-auto grow-0 min-h-0 gap-y-[normal] text-clip text-wrap md:text-[lab(7.78201_-0.0000149012_0)] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <span className="box-content caret-black inline min-h-0 min-w-0 text-clip text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  Can I upgrade to the annual plan and get the
                                  discount applied retroactively?
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <div className="[align-items:normal] box-content caret-black gap-x-[normal] block justify-normal min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:justify-end md:min-h-[auto] md:min-w-[102px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              <span className="text-black text-base box-content caret-black inline shrink leading-[normal] min-h-0 min-w-0 pr-0 md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.4)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:block md:shrink-0 md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-2 md:scroll-m-0 md:scroll-p-[auto]">
                                6:23 AM
                              </span>
                              <span className="bg-transparent box-content caret-black inline h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-orange-600 md:box-border md:caret-transparent md:block md:h-1.5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-1.5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px]"></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="box-content caret-black md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <div className="static text-base [align-items:normal] box-content caret-black gap-x-[normal] block leading-[normal] gap-y-[normal] rounded-none md:relative md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:leading-5 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-2 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm">
                          <div className="static box-content caret-black min-h-0 min-w-0 md:relative md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <span className="static shadow-none box-content caret-black inline shrink h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,lab(98.84_0.0000298023_-0.0000119209)_0px_0px_0px_1px,lab(90.952_0_-0.0000119209)_0px_0px_0px_2px,rgba(0,0,0,0)_0px_0px_0px_0px] md:box-border md:caret-transparent md:flex md:shrink-0 md:h-8 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-8 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm">
                              <span className="[align-items:normal] box-content caret-black inline h-auto justify-normal min-h-0 min-w-0 pointer-events-auto w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-full md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <div className="static text-black [align-items:normal] bg-transparent box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto md:relative md:items-center md:aspect-auto md:bg-[oklab(0.951341_-0.0447635_0.143715_/_0.2)] md:box-border md:caret-transparent md:flex md:h-full md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  <div className="static bg-none box-content caret-black z-auto inset-auto md:absolute md:aspect-auto md:bg-[radial-gradient(100%_100%,rgba(255,255,255,0.15)_0%,rgba(0,0,0,0)_60%)] md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                                  <div className="static [align-items:normal] box-content caret-black block flex-row justify-normal transform-none z-auto inset-auto md:absolute md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
                                    <img
                                      src="https://c.animaapp.com/mlnjf5yy2zLUvi/assets/icon-6.svg"
                                      alt="Icon"
                                      className="box-content caret-black w-auto md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-3/5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                                    />
                                    <span className="text-base box-content caret-black inline leading-[normal] min-h-0 min-w-0 mt-0 md:text-[8.32px] md:aspect-auto md:box-border md:caret-transparent md:block md:leading-[8.32px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[8%] md:scroll-m-0 md:scroll-p-[auto]">
                                      N
                                    </span>
                                  </div>
                                </div>
                              </span>
                            </span>
                            <div className="static bg-transparent shadow-none box-content caret-black h-auto w-auto rounded-none right-auto bottom-auto md:absolute md:aspect-auto md:bg-emerald-500 md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,lab(98.84_0.0000298023_-0.0000119209)_0px_0px_0px_2px,rgba(0,0,0,0)_0px_0px_0px_0px] md:box-border md:caret-transparent md:h-[5px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[5px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px] md:-right-1 md:bottom-0.5"></div>
                          </div>
                          <div className="[align-items:normal] box-content caret-black gap-x-[normal] block basis-auto grow-0 min-h-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <p className="box-content caret-black shrink max-w-none min-h-0 min-w-0 text-clip normal-case text-wrap md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:max-w-[140px] md:min-h-[auto] md:min-w-[140px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:capitalize md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              Nico Jeannen
                            </p>
                            <div className="[align-items:normal] box-content caret-black gap-x-[normal] block basis-auto grow-0 min-h-0 gap-y-[normal] pr-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-6 md:scroll-m-0 md:scroll-p-[auto]">
                              <span className="text-black [align-items:normal] box-content caret-black gap-x-[normal] inline basis-auto grow-0 min-h-0 gap-y-[normal] text-clip text-wrap md:text-[lab(7.78201_-0.0000149012_0)] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <span className="box-content caret-black inline min-h-0 min-w-0 text-clip text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  I just paid for the annual plan but still see
                                  the free tier in my dashboard. Help!
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <span className="text-black text-base font-normal box-content caret-black inline shrink leading-[normal] min-h-0 min-w-0 md:text-orange-600 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:block md:shrink-0 md:leading-3 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              12h waiting
                            </span>
                            <div className="[align-items:normal] box-content caret-black gap-x-[normal] block justify-normal min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:justify-end md:min-h-[auto] md:min-w-[102px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              <span className="text-black text-base box-content caret-black inline shrink leading-[normal] min-h-0 min-w-0 pr-0 md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.4)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:block md:shrink-0 md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-2 md:scroll-m-0 md:scroll-p-[auto]">
                                9:23 PM
                              </span>
                              <span className="bg-transparent box-content caret-black inline h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-orange-600 md:box-border md:caret-transparent md:block md:h-1.5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-1.5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px]"></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="box-content caret-black md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <div className="static text-base [align-items:normal] box-content caret-black gap-x-[normal] block leading-[normal] gap-y-[normal] rounded-none md:relative md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:leading-5 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-2 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm">
                          <div className="static box-content caret-black min-h-0 min-w-0 md:relative md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <span className="static shadow-none box-content caret-black inline shrink h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,lab(98.84_0.0000298023_-0.0000119209)_0px_0px_0px_1px,lab(90.952_0_-0.0000119209)_0px_0px_0px_2px,rgba(0,0,0,0)_0px_0px_0px_0px] md:box-border md:caret-transparent md:flex md:shrink-0 md:h-8 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-8 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm">
                              <span className="[align-items:normal] box-content caret-black inline h-auto justify-normal min-h-0 min-w-0 pointer-events-auto w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-full md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <div className="static text-black [align-items:normal] bg-transparent box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto md:relative md:items-center md:aspect-auto md:bg-[oklab(0.608388_0.155916_0.122386_/_0.2)] md:box-border md:caret-transparent md:flex md:h-full md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  <div className="static bg-none box-content caret-black z-auto inset-auto md:absolute md:aspect-auto md:bg-[radial-gradient(100%_100%,rgba(255,255,255,0.15)_0%,rgba(0,0,0,0)_60%)] md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                                  <div className="static [align-items:normal] box-content caret-black block flex-row justify-normal transform-none z-auto inset-auto md:absolute md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
                                    <img
                                      src="https://c.animaapp.com/mlnjf5yy2zLUvi/assets/icon-7.svg"
                                      alt="Icon"
                                      className="box-content caret-black w-auto md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-3/5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                                    />
                                    <span className="text-base box-content caret-black inline leading-[normal] min-h-0 min-w-0 mt-0 md:text-[8.32px] md:aspect-auto md:box-border md:caret-transparent md:block md:leading-[8.32px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[8%] md:scroll-m-0 md:scroll-p-[auto]">
                                      D
                                    </span>
                                  </div>
                                </div>
                              </span>
                            </span>
                          </div>
                          <div className="[align-items:normal] box-content caret-black gap-x-[normal] block basis-auto grow-0 min-h-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <p className="box-content caret-black shrink max-w-none min-h-0 min-w-0 text-clip normal-case text-wrap md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:max-w-[140px] md:min-h-[auto] md:min-w-[140px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:capitalize md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              Danny Postma
                            </p>
                            <div className="[align-items:normal] box-content caret-black gap-x-[normal] block basis-auto grow-0 min-h-0 gap-y-[normal] pr-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-6 md:scroll-m-0 md:scroll-p-[auto]">
                              <span className="text-black [align-items:normal] box-content caret-black gap-x-[normal] inline basis-auto grow-0 min-h-0 gap-y-[normal] text-clip text-wrap md:text-[lab(48.496_0_0)] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <span className="box-content caret-black inline min-h-0 min-w-0 text-clip text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  We&#39;re adding dark mode support in the next
                                  release! I&#39;ll update you when it&#39;s
                                  ready.
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <div className="[align-items:normal] box-content caret-black gap-x-[normal] block justify-normal min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:justify-end md:min-h-[auto] md:min-w-[102px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              <span className="text-black text-base box-content caret-black inline shrink leading-[normal] min-h-0 min-w-0 pr-0 md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.4)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:block md:shrink-0 md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-2 md:scroll-m-0 md:scroll-p-[auto]">
                                1d
                              </span>
                              <span className="bg-transparent box-content caret-black inline h-auto min-h-0 min-w-0 opacity-100 w-auto rounded-none md:aspect-auto md:bg-orange-600 md:box-border md:caret-transparent md:block md:h-1.5 md:min-h-[auto] md:min-w-[auto] md:opacity-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-1.5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px]"></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="box-content caret-black md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <div className="static text-base [align-items:normal] box-content caret-black gap-x-[normal] block leading-[normal] gap-y-[normal] rounded-none md:relative md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:leading-5 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-2 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm">
                          <div className="static box-content caret-black min-h-0 min-w-0 md:relative md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <span className="static shadow-none box-content caret-black inline shrink h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,lab(98.84_0.0000298023_-0.0000119209)_0px_0px_0px_1px,lab(90.952_0_-0.0000119209)_0px_0px_0px_2px,rgba(0,0,0,0)_0px_0px_0px_0px] md:box-border md:caret-transparent md:flex md:shrink-0 md:h-8 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-8 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm">
                              <span className="[align-items:normal] box-content caret-black inline h-auto justify-normal min-h-0 min-w-0 pointer-events-auto w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-full md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <div className="static text-black [align-items:normal] bg-transparent box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto md:relative md:items-center md:aspect-auto md:bg-[oklab(0.81222_0.140873_-0.0622125_/_0.2)] md:box-border md:caret-transparent md:flex md:h-full md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  <div className="static bg-none box-content caret-black z-auto inset-auto md:absolute md:aspect-auto md:bg-[radial-gradient(100%_100%,rgba(255,255,255,0.15)_0%,rgba(0,0,0,0)_60%)] md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                                  <div className="static [align-items:normal] box-content caret-black block flex-row justify-normal transform-none z-auto inset-auto md:absolute md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
                                    <img
                                      src="https://c.animaapp.com/mlnjf5yy2zLUvi/assets/icon-8.svg"
                                      alt="Icon"
                                      className="box-content caret-black w-auto md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-3/5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                                    />
                                    <span className="text-base box-content caret-black inline leading-[normal] min-h-0 min-w-0 mt-0 md:text-[8.32px] md:aspect-auto md:box-border md:caret-transparent md:block md:leading-[8.32px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[8%] md:scroll-m-0 md:scroll-p-[auto]">
                                      T
                                    </span>
                                  </div>
                                </div>
                              </span>
                            </span>
                          </div>
                          <div className="[align-items:normal] box-content caret-black gap-x-[normal] block basis-auto grow-0 min-h-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <p className="box-content caret-black shrink max-w-none min-h-0 min-w-0 text-clip normal-case text-wrap md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:max-w-[140px] md:min-h-[auto] md:min-w-[140px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:capitalize md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              Tony Dinh
                            </p>
                            <div className="[align-items:normal] box-content caret-black gap-x-[normal] block basis-auto grow-0 min-h-0 gap-y-[normal] pr-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-6 md:scroll-m-0 md:scroll-p-[auto]">
                              <span className="text-black [align-items:normal] box-content caret-black gap-x-[normal] inline basis-auto grow-0 min-h-0 gap-y-[normal] text-clip text-wrap md:text-[lab(7.78201_-0.0000149012_0)] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <span className="box-content caret-black inline min-h-0 min-w-0 text-clip text-wrap md:aspect-auto md:box-border md:caret-transparent md:block md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  Perfect! Exactly what I needed. Thanks!
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="[align-items:normal] box-content caret-black gap-x-[normal] block min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <span className="text-black text-base font-normal box-content caret-black inline shrink leading-[normal] min-h-0 min-w-0 md:text-orange-600 md:text-xs md:font-medium md:aspect-auto md:box-border md:caret-transparent md:block md:shrink-0 md:leading-3 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              2d waiting
                            </span>
                            <div className="[align-items:normal] box-content caret-black gap-x-[normal] block justify-normal min-h-0 min-w-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-1 md:flex md:justify-end md:min-h-[auto] md:min-w-[102px] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-1 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              <span className="text-black text-base box-content caret-black inline shrink leading-[normal] min-h-0 min-w-0 pr-0 md:text-[oklab(0.205_-0.00000207871_0.00000478327_/_0.4)] md:text-xs md:aspect-auto md:box-border md:caret-transparent md:block md:shrink-0 md:leading-4 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-2 md:scroll-m-0 md:scroll-p-[auto]">
                                2d
                              </span>
                              <span className="bg-transparent box-content caret-black inline h-auto min-h-0 min-w-0 w-auto rounded-none md:aspect-auto md:bg-orange-600 md:box-border md:caret-transparent md:block md:h-1.5 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-1.5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px]"></span>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="box-content caret-black md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <div className="static text-base [align-items:normal] box-content caret-black gap-x-[normal] block leading-[normal] gap-y-[normal] rounded-none md:relative md:text-sm md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-3 md:flex md:leading-5 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-3 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:p-2 md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm">
                          <div className="static box-content caret-black min-h-0 min-w-0 md:relative md:aspect-auto md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <span className="static shadow-none box-content caret-black inline shrink h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,lab(98.84_0.0000298023_-0.0000119209)_0px_0px_0px_1px,lab(90.952_0_-0.0000119209)_0px_0px_0px_2px,rgba(0,0,0,0)_0px_0px_0px_0px] md:box-border md:caret-transparent md:flex md:shrink-0 md:h-8 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-8 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-sm">
                              <span className="[align-items:normal] box-content caret-black inline h-auto justify-normal min-h-0 min-w-0 pointer-events-auto w-auto md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:h-full md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                <div className="static text-black [align-items:normal] bg-transparent box-content caret-black block h-auto justify-normal min-h-0 min-w-0 w-auto md:relative md:items-center md:aspect-auto md:bg-[oklab(0.81222_0.140873_-0.0622125_/_0.2)] md:box-border md:caret-transparent md:flex md:h-full md:justify-center md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                                  <div className="static bg-none box-content caret-black z-auto inset-auto md:absolute md:aspect-auto md:bg-[radial-gradient(100%_100%,rgba(255,255,255,0.15)_0%,rgba(0,0,0,0)_60%)] md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                                  <div className="static [align-items:normal] box-content caret-black block flex-row justify-normal transform-none z-auto inset-auto md:absolute md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
                                    <img
                                      src="https://c.animaapp.com/mlnjf5yy2zLUvi/assets/icon-8.svg"
                                      alt="Icon"
                                      className="box-content caret-black w-auto md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-3/5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
                                    />
                                    <span className="text-base box-content caret-black inline leading-[normal] min-h-0 min-w-0 mt-0 md:text-[8.32px] md:aspect-auto md:box-border md:caret-transparent md:block md:leading-[8.32px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mt-[8%] md:scroll-m-0 md:scroll-p-[auto]">
                                      D
                                    </span>
                                  </div>
                                </div>
                              </span>
                            </span>
                          </div>
                          <div className="[align-items:normal] box-content caret-black gap-x-[normal] block basis-auto grow-0 min-h-0 gap-y-[normal] md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                            <p className="box-content caret-black shrink max-w-none min-h-0 min-w-0 text-clip normal-case text-wrap md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:max-w-[140px] md:min-h-[auto] md:min-w-[140px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:text-ellipsis md:capitalize md:underline-offset-auto md:text-nowrap md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                              Damon Chen
                            </p>
                            <div className="[align-items:normal] box-content caret-black gap-x-[normal] block basis-auto grow-0 min-h-0 gap-y-[normal] pr-0 md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:basis-[0%] md:grow md:min-h-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pr-6 md:scroll-m-0 md:scroll-p-[auto]">
                              <span></span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
